config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  root 'articles#index'
  resources :articles do
  resources :comments
end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    mount_uploader :image , ImageUploader
    has_many :comments , dependent: :destroy
    after_destroy :log_destroy_action
    def log_destroy_action
        puts 'Article destroyed'
    end

   




    validates :name ,format: { with: /\A[a-zA-Z]+\z/, message: 'only letters are acceptable'}
    validates :password, numericality: true
    validates :email, uniqueness: true ,format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i , message: "is not valid"}
    validates :username ,uniqueness:{message: ->(data) do " #{data[:value]} is already taken" 
    end}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article , dependent: :destroy


end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end
    def archived?
status == 'archived'
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin_user!
  def index
    @articles=Article.all
  end
def show
@article=Article.find(params[:id])
end
def new
  @article=Article.new
end
def create
  @article=Article.new(article_params)
  if @article.save 
    redirect_to @article
  else
    render :new, status: :unprocessable_entity
  end
end
def edit
  @article=Article.find(params[id:])
end
def update
  @article=Article.find(params[id:])
  if @article.update(article_params)
    redirect_to @article
  else
    render :edit, status: :unprocessable_entity
  end
end
def destroy
  @article=Article.find(params[:id])
  @article.destroy
  redirect_to root_path, status: :see_other
end
private
def article_params
params.require(:article).permit(:name,:gender,:email,:password, :user_age,:username,:image,:status)
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article=Article.find(params[:article_id])
        @comment=@article.comments.create(comment_params)
        redirect_to article_path(@article)
    end
    private
    def comment_params
        params.require(:comment).permit(:commenter,:body,:status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/index.html.erb
<%if admin_user_signed_in?%>
<%= link_to "Sign Out", destroy_admin_user_session_path , method: :delete %>
<%else%>
<%= link_to "Sign In", new_admin_user_session_path%>
<% end%>
<h1>All Data</h1> 
<%@articles.each do |article|%>

<%= link_to article.name, article %><br><br>
<%end%>
<button><%= link_to "New Article", new_article_path%></button>

app/views/articles/new.html.erb
<h1>Create New Article</h1>

<%=form_with model: @article do |form|%>

<div>
<%=form.label :name%><br>
<%=form.text_field :name%>
<%@article.errors.full_messages_for(:name).each do |message|%>
<div><%=message%></div>
<%end%>
</div>
<div><%=form.label :gender%><br>
<%=form.text_field :gender%>
</div>
<div><%=form.label :user_age%><br>
<%=form.text_field :user_age%>
<%@article.errors.full_messages_for(:user_age).each do |message|%>
<div><%=message%></div>
<%end%>
<div><%=form.label :email%><br>
<%=form.text_field :email%>
<%@article.errors.full_messages_for(:email).each do |message|%>
<div><%=message%></div>
<%end%>
</div><br>
<div>
<div><%=form.label :password%><br>
<%=form.password_field :password%>
</div>
<%@article.errors.full_messages_for(:password).each do |message|%>
<div><%=message%></div>
<%end%><br>
<div><%=form.label :username%><br>
<%=form.text_field :username%>
</div>
<%@article.errors.full_messages_for(:username).each do |message|%>
<div><%=message%></div>
<button>
<%end%>
<%=form.label :image%>
<%=form.file_field :image%>
<%=form.submit%></button>
<%end%>

app/views/articles/show.html.erb
<%=@article.name%>
<%=@article.gender%>
<%=@article.email%>
<%=@article.password%>
<%=@article.user_age%>
<%=@article.username%><br>
<%=link_to "Edit Article", new_article_path%>
<%= link_to "Delete", article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Are You sure"
} %>

<h2>comments</h2>
<%@article.comments.each do |comment|%>
<p>
<h4>commenter:</h4>
<%=comment.commenter%>
</p>
<p>
<h4>comments:</h4>
<%=comment.body%>
</p>
<%end%>
<h2>Add a comment:</h2>
<%=form_with model: [@article, @article.comments.build] do |form|%>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<%end%>
<%=image_tag @article.image.url if @article.image?%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gondal2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>